#!/usr/bin/env bash
# build_android_native.sh — Build Concord as an Android APK via Tauri v2.
#
# Designed to run on orrion (CachyOS, RTX 3070). Produces either a debug
# APK (fast iteration) or a signed release APK suitable for distribution.
#
# Companion to scripts/build_ios_native.sh and scripts/build_macos_native.sh.
# Same shape, same exit codes, same env-var discipline.
#
# =================================================================
# Required environment (release builds only — debug builds work
# without signing credentials):
# =================================================================
#
#   KEYSTORE_PATH       — Absolute path to the .jks / .keystore signing file
#   KEYSTORE_PASS       — Keystore password
#   KEY_ALIAS           — Key alias within the keystore
#   KEY_PASS            — Key password (defaults to KEYSTORE_PASS if unset)
#
# Optional:
#
#   ANDROID_HOME        — Android SDK root (auto-detected from common locations
#                         if unset: ~/Android/Sdk, /usr/lib/android-sdk)
#   ANDROID_NDK_HOME    — Android NDK root (auto-detected from ANDROID_HOME/ndk/*)
#   RELEASE_DIR         — Override output directory. Defaults to
#                         ${REPO_ROOT}/dist/android-release (release) or
#                         ${REPO_ROOT}/dist/android-debug (debug)
#
# =================================================================
# Usage:
# =================================================================
#
#   scripts/build_android_native.sh              # release APK (requires signing env vars)
#   scripts/build_android_native.sh --debug      # debug APK (unsigned, fast)
#   scripts/build_android_native.sh --release    # explicit release (same as default)
#
# =================================================================
# Android scaffolding:
# =================================================================
#
# The Android project lives in src-tauri/gen/android/. That directory
# was seeded with a template layout at repo init time, but the actual
# build.gradle and source files are generated by `cargo tauri android init`,
# which must be run once on a host with the Android SDK installed:
#
#   cd src-tauri
#   cargo tauri android init
#
# After init, `cargo tauri android build` produces the APK. See
# client/NATIVE_BUILD.md §7 for the full scaffolding guide.
#
# =================================================================
# Exit codes:
# =================================================================
#
#   0  build succeeded (artifact is in $RELEASE_DIR)
#   1  missing prerequisite tool, env var, or Android project
#   2  cargo tauri build failed
#   3  signing or post-processing failed
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SRC_TAURI="${REPO_ROOT}/src-tauri"
CLIENT_DIR="${REPO_ROOT}/client"
ANDROID_GEN_DIR="${SRC_TAURI}/gen/android"

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
log()  { printf '\033[1;36m[build_android]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[build_android]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[build_android ERROR]\033[0m %s\n' "$*" >&2; exit "${2:-1}"; }

require_tool() {
    local tool="$1"
    local hint="$2"
    if ! command -v "${tool}" >/dev/null 2>&1; then
        die "missing required tool '${tool}'. ${hint}" 1
    fi
}

require_env() {
    local var="$1"
    if [[ -z "${!var:-}" ]]; then
        die "required environment variable ${var} is not set" 1
    fi
}

# Auto-detect ANDROID_HOME if not set
if [[ -z "${ANDROID_HOME:-}" ]]; then
    for candidate in \
        "${HOME}/Android/Sdk" \
        "${HOME}/android-sdk" \
        "/usr/lib/android-sdk" \
        "/opt/android-sdk"; do
        if [[ -d "${candidate}" ]]; then
            export ANDROID_HOME="${candidate}"
            log "Auto-detected ANDROID_HOME=${ANDROID_HOME}"
            break
        fi
    done
fi

# Auto-detect ANDROID_NDK_HOME from ANDROID_HOME if not set
if [[ -z "${ANDROID_NDK_HOME:-}" && -n "${ANDROID_HOME:-}" ]]; then
    # Prefer the highest-numbered NDK installed
    local_ndk=""
    if [[ -d "${ANDROID_HOME}/ndk" ]]; then
        local_ndk="$(ls -d "${ANDROID_HOME}/ndk/"*/ 2>/dev/null | sort -V | tail -n1)"
    fi
    if [[ -n "${local_ndk}" ]]; then
        export ANDROID_NDK_HOME="${local_ndk%/}"
        log "Auto-detected ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
    fi
fi

# ----------------------------------------------------------------------------
# Arg parsing
# ----------------------------------------------------------------------------
PROFILE="release"        # release | debug
PROFILE_EXPLICIT=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --debug)
            PROFILE="debug"
            PROFILE_EXPLICIT=1
            shift
            ;;
        --release)
            PROFILE="release"
            PROFILE_EXPLICIT=1
            shift
            ;;
        -h|--help)
            sed -n '2,55p' "${BASH_SOURCE[0]}" | sed 's/^# //; s/^#$//'
            exit 0
            ;;
        *)
            die "unknown argument: $1" 1
            ;;
    esac
done

# Default RELEASE_DIR depends on profile.
if [[ "${PROFILE}" == "debug" ]]; then
    RELEASE_DIR="${RELEASE_DIR:-${REPO_ROOT}/dist/android-debug}"
else
    RELEASE_DIR="${RELEASE_DIR:-${REPO_ROOT}/dist/android-release}"
fi

# ----------------------------------------------------------------------------
# Platform check
# ----------------------------------------------------------------------------
if [[ "$(uname -s)" != "Linux" ]]; then
    warn "This script is designed for Linux (orrion). Current uname: $(uname -s)"
    warn "Android builds may work on macOS/Windows but are not tested."
fi

# ----------------------------------------------------------------------------
# Prerequisites
# ----------------------------------------------------------------------------
log "Checking prerequisites..."
require_tool cargo  "Install Rust: https://rustup.rs/"
require_tool node   "Install Node 18+ via nvm or distro package manager"
require_tool java   "Install JDK 17+: sudo pacman -S jdk17-openjdk"

if ! cargo tauri --version >/dev/null 2>&1; then
    die "tauri-cli is not installed. Run: cargo install tauri-cli --version '^2.0' --locked" 1
fi

if [[ -z "${ANDROID_HOME:-}" ]]; then
    die "ANDROID_HOME is not set and could not be auto-detected.
Set ANDROID_HOME to your Android SDK root (e.g. ~/Android/Sdk).
See client/NATIVE_BUILD.md §7 for the full Android setup guide." 1
fi

if [[ ! -d "${ANDROID_HOME}" ]]; then
    die "ANDROID_HOME='${ANDROID_HOME}' does not exist" 1
fi

if [[ -z "${ANDROID_NDK_HOME:-}" ]]; then
    die "ANDROID_NDK_HOME is not set and could not be auto-detected.
Install the Android NDK via Android Studio > SDK Manager > SDK Tools > NDK." 1
fi

if [[ ! -d "${ANDROID_NDK_HOME}" ]]; then
    die "ANDROID_NDK_HOME='${ANDROID_NDK_HOME}' does not exist" 1
fi

# Check Rust Android targets.
REQUIRED_TARGETS=(
    aarch64-linux-android
    armv7-linux-androideabi
    i686-linux-android
    x86_64-linux-android
)
for target in "${REQUIRED_TARGETS[@]}"; do
    if ! rustup target list --installed 2>/dev/null | grep -qx "${target}"; then
        log "Installing Rust target ${target}"
        rustup target add "${target}"
    fi
done

# Release builds require signing credentials. Debug builds skip signing.
SIGNED_BUILD=0
if [[ "${PROFILE}" == "release" ]]; then
    if [[ -n "${KEYSTORE_PATH:-}" && -n "${KEYSTORE_PASS:-}" && -n "${KEY_ALIAS:-}" ]]; then
        if [[ ! -f "${KEYSTORE_PATH}" ]]; then
            die "KEYSTORE_PATH='${KEYSTORE_PATH}' does not exist" 1
        fi
        SIGNED_BUILD=1
        KEY_PASS="${KEY_PASS:-${KEYSTORE_PASS}}"
        log "Release build mode: SIGNED (keystore=${KEYSTORE_PATH}, alias=${KEY_ALIAS})"
    else
        warn "KEYSTORE_PATH / KEYSTORE_PASS / KEY_ALIAS unset — producing UNSIGNED release APK."
        warn "Unsigned APKs must be signed before distribution (Play Store / direct install)."
    fi
fi

log "cargo:          $(cargo --version)"
log "rustc:          $(rustc --version)"
log "tauri-cli:      $(cargo tauri --version)"
log "java:           $(java -version 2>&1 | head -n1)"
log "ANDROID_HOME:   ${ANDROID_HOME}"
log "ANDROID_NDK:    ${ANDROID_NDK_HOME}"
log "profile:        ${PROFILE}"
log "release_dir:    ${RELEASE_DIR}"

# ----------------------------------------------------------------------------
# The Android project must exist. It is generated by `cargo tauri android init`
# and partially committed via templates — if the actual project files are
# missing, run the one-time init step first.
# ----------------------------------------------------------------------------
# We check for app/src/main/ rather than a build.gradle — the template
# layout populates the directory before init, but the actual Kotlin/Java
# sources land after init.
if [[ ! -d "${ANDROID_GEN_DIR}/app/src/main" ]]; then
    die "Android project not found at ${ANDROID_GEN_DIR}/app/src/main.
Run 'cd src-tauri && cargo tauri android init' first (one-time setup on orrion).
See client/NATIVE_BUILD.md §7 for the full scaffolding guide." 1
fi

# ----------------------------------------------------------------------------
# Build the React client first
# ----------------------------------------------------------------------------
log "Building React client (${CLIENT_DIR})..."
pushd "${CLIENT_DIR}" >/dev/null
if [[ ! -d node_modules ]] \
   || [[ ! -f node_modules/.package-lock.json ]] \
   || [[ package-lock.json -nt node_modules/.package-lock.json ]]; then
    log "node_modules is missing or stale — running npm ci"
    npm ci
fi
npm run build
popd >/dev/null

# ----------------------------------------------------------------------------
# Run cargo tauri android build
# ----------------------------------------------------------------------------
TAURI_ARGS=(android build)
if [[ "${PROFILE}" == "debug" ]]; then
    TAURI_ARGS+=(--debug)
fi

# Wire signing credentials into the environment that Tauri passes to Gradle.
# Tauri v2 reads these as TAURI_ANDROID_* (see tauri-cli source):
#   TAURI_ANDROID_KEYSTORE_PATH — path to keystore file
#   TAURI_ANDROID_KEYSTORE_PASSWORD — keystore password
#   TAURI_ANDROID_KEY_ALIAS — key alias
#   TAURI_ANDROID_KEY_PASSWORD — key password
if [[ "${SIGNED_BUILD}" -eq 1 ]]; then
    export TAURI_ANDROID_KEYSTORE_PATH="${KEYSTORE_PATH}"
    export TAURI_ANDROID_KEYSTORE_PASSWORD="${KEYSTORE_PASS}"
    export TAURI_ANDROID_KEY_ALIAS="${KEY_ALIAS}"
    export TAURI_ANDROID_KEY_PASSWORD="${KEY_PASS}"
fi

log "Running: cargo tauri ${TAURI_ARGS[*]}"
pushd "${SRC_TAURI}" >/dev/null
if ! cargo tauri "${TAURI_ARGS[@]}"; then
    die "cargo tauri android build failed" 2
fi
popd >/dev/null

# ----------------------------------------------------------------------------
# Locate artifacts
# ----------------------------------------------------------------------------
#
# Tauri v2 places the final APK at:
#   src-tauri/gen/android/app/build/outputs/apk/release/app-release.apk
#   src-tauri/gen/android/app/build/outputs/apk/debug/app-debug.apk
#
APK_SUBDIR="${PROFILE}"
APK_SUFFIX="${PROFILE}"
APK_DIR="${ANDROID_GEN_DIR}/app/build/outputs/apk/${APK_SUBDIR}"
APK_FILE="${APK_DIR}/app-${APK_SUFFIX}.apk"

# Fallback: Tauri may name the APK app-release-unsigned.apk for unsigned builds
APK_FILE_UNSIGNED="${APK_DIR}/app-${APK_SUFFIX}-unsigned.apk"

if [[ ! -f "${APK_FILE}" && -f "${APK_FILE_UNSIGNED}" ]]; then
    APK_FILE="${APK_FILE_UNSIGNED}"
fi

if [[ ! -f "${APK_FILE}" ]]; then
    # Generic fallback search
    APK_FILE="$(find "${ANDROID_GEN_DIR}/app/build/outputs/apk" -name "*.apk" | sort | tail -n1 || true)"
    if [[ -z "${APK_FILE}" ]]; then
        die "APK not found in ${ANDROID_GEN_DIR}/app/build/outputs/apk/. Build may have failed silently." 1
    fi
    warn "Using fallback APK path: ${APK_FILE}"
fi

# ----------------------------------------------------------------------------
# Copy to dist/
# ----------------------------------------------------------------------------
mkdir -p "${RELEASE_DIR}"
cp "${APK_FILE}" "${RELEASE_DIR}/concord.apk"

log "==================================================================="
log "Build complete."
log "  APK: ${RELEASE_DIR}/concord.apk"
if [[ "${SIGNED_BUILD}" -eq 0 ]]; then
    log ""
    log "  NOTE: This is an UNSIGNED APK."
    if [[ "${PROFILE}" == "release" ]]; then
        log "  Sign it before distribution:"
        log "    apksigner sign --ks \$KEYSTORE_PATH --ks-key-alias \$KEY_ALIAS \\"
        log "      --ks-pass pass:\$KEYSTORE_PASS \\"
        log "      ${RELEASE_DIR}/concord.apk"
    else
        log "  Install directly on a connected device:"
        log "    adb install ${RELEASE_DIR}/concord.apk"
    fi
fi
log "==================================================================="
